-- ============================================================
-- 051: client_recording_shares — token-based sharing (Faza 7)
-- ============================================================
--
-- BACKGROUND
-- PR #1 removed the placebo sharing UI ("Prywatne / Polubieni / Zaproszeni / Wszyscy"
-- buttons that did nothing). This migration + sibling commits reintroduce sharing
-- with a real backend, but with a simpler, defensible model than the original four
-- opaque modes:
--
--   - 'private'        — default, only owner can see (implicit, no row in this table)
--   - 'link'           — owner generates a time-limited link (7 days default)
--   - 'link_permanent' — owner generates an indefinite link (until revoked)
--
-- Why not 'favorites' / 'invited' / 'public'?
--   - 'favorites' requires a friend model which HTG2 doesn't have
--   - 'invited' requires an invitation + email + accepted_at model (complex)
--   - 'public' is dangerous — any indexed CDN URL becomes discoverable
--
-- Token-based sharing is simpler and safer:
--   - Owner controls exactly who gets a link (they send it)
--   - Link can be revoked anytime
--   - Links can expire automatically (7-day default)
--   - Public endpoint signs a short-lived Bunny CDN URL (15 min TTL) with
--     Content-Disposition: attachment — forces download, neutralizes the
--     "malware hosted on our domain" risk from the magic-bytes limitation
--
-- TABLE DESIGN
--
-- One row per generated share token. Multiple tokens per recording are allowed
-- (owner may want to share with different audiences at different times). Revoke
-- via DELETE endpoint drops all active tokens for a recording.
--
-- Tokens are cryptographically random (generated by the API, not the DB) — this
-- migration only stores them.

CREATE TABLE IF NOT EXISTS public.client_recording_shares (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- CASCADE: if the recording is deleted (soft or hard), all its share tokens
  -- become moot — drop them immediately so the public endpoint returns 404.
  recording_id  UUID        NOT NULL REFERENCES public.client_recordings(id) ON DELETE CASCADE,

  -- Who generated the token. CASCADE: if the user deletes their account,
  -- all their generated tokens go with them (RODO art. 17).
  created_by    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- The random token the owner shares via a link. Not a JWT — just a random
  -- opaque string the public endpoint looks up. Length is enforced at the API
  -- layer (crypto.randomBytes(32).toString('base64url') = 43 chars).
  token         TEXT        NOT NULL UNIQUE,

  -- Expiration: NULL means permanent (until manually revoked).
  -- For time-limited shares, the API sets this to now() + 7 days.
  expires_at    TIMESTAMPTZ,

  -- Soft revoke: once set, the token is rejected by the public endpoint even
  -- if expires_at is still in the future. Kept for audit trail.
  revoked_at    TIMESTAMPTZ,
  revoked_by    UUID        REFERENCES auth.users(id) ON DELETE SET NULL,

  created_at    TIMESTAMPTZ DEFAULT now()
);

-- Lookup by token (the public endpoint's only query).
-- Partial index: only non-revoked tokens need fast lookup.
CREATE INDEX idx_crs_token
  ON public.client_recording_shares(token)
  WHERE revoked_at IS NULL;

-- Find all shares for a recording (owner's "manage shares" view, revoke flow).
CREATE INDEX idx_crs_recording
  ON public.client_recording_shares(recording_id);

-- Find shares created by a specific user (audit, bulk revoke on user delete).
CREATE INDEX idx_crs_created_by
  ON public.client_recording_shares(created_by);

-- RLS: same pattern as every other client_recordings-adjacent table —
-- enabled, zero policies for non-service_role.
ALTER TABLE public.client_recording_shares ENABLE ROW LEVEL SECURITY;

-- End-state assertion.
DO $$
DECLARE
  policy_count int;
BEGIN
  SELECT count(*) INTO policy_count
  FROM pg_policies
  WHERE schemaname = 'public'
    AND tablename = 'client_recording_shares'
    AND NOT (roles = ARRAY['service_role']::name[]);

  IF policy_count > 0 THEN
    RAISE EXCEPTION
      'client_recording_shares should have 0 non-service_role policies after migration, found %',
      policy_count;
  END IF;
END $$;
