-- Migration 088: Session waveform peaks URL
-- ==========================================
-- Stores a URL to a pre-computed waveform peaks file (JSON/binary) for
-- session_templates. Used by the admin fragment editor to render a waveform
-- ruler without real-time decoding. Generated by a background job after
-- Bunny Stream encodes the video.

ALTER TABLE public.session_templates
  ADD COLUMN IF NOT EXISTS waveform_peaks_url TEXT;

COMMENT ON COLUMN public.session_templates.waveform_peaks_url IS
  'URL to pre-computed waveform peaks (JSON). Populated by background job post-encoding. NULL = waveform not yet available; editor falls back to ruler-only display.';
